// PULSE/ — i18n strings + mock data

window.I18N = {
  es: {
    appName: 'PULSE/',
    tagline: 'Entrenamiento. Nutrición. Resultados.',
    perspective: { client: 'Cliente', coach: 'Entrenador' },
    nav: {
      group_main: 'Principal',
      home: 'Inicio',
      routine: 'Rutina',
      meals: 'Alimentación',
      progress: 'Progreso',
      calendar: 'Calendario',
      group_other: 'Más',
      messages: 'Mensajes',
      settings: 'Ajustes',
      // coach
      group_coach: 'Coaching',
      clients: 'Clientes',
      sessions: 'Sesiones',
      library: 'Biblioteca',
      plans: 'Plantillas',
    },
    search: 'Buscar ejercicio, comida, cliente…',
    greeting_morning: 'Buenos días',
    greeting_afternoon: 'Buenas tardes',
    greeting_evening: 'Buenas noches',
    today: 'Hoy',
    week: 'Esta semana',
    streak: 'racha',
    days_short: 'd',
    phase: 'Fase',
    phases: { hyper: 'Hipertrofia', cut: 'Definición', maint: 'Mantenimiento', strength: 'Fuerza' },
    objective: 'Objetivo',
    objectives: { lose: 'Perder grasa', gain: 'Ganar músculo', maint: 'Mantener' },
    day_n: 'Día',
    of: 'de',
    // routine
    todays_routine: 'Rutina de hoy',
    routine_meta: 'ejercicios',
    minutes: 'min',
    start_workout: 'Empezar entreno',
    finish_workout: 'Finalizar',
    sets: 'Series',
    reps: 'Reps',
    weight: 'Peso',
    rest: 'Descanso',
    rest_label: 'Descanso',
    set_num: 'Set',
    last_session: 'Última sesión',
    pr: 'PR',
    notes: 'Notas',
    set_done: 'Hecho',
    // meals
    nutrition: 'Nutrición',
    calories: 'Calorías',
    kcal: 'kcal',
    macro_p: 'Proteína',
    macro_c: 'Carbos',
    macro_f: 'Grasa',
    g_unit: 'g',
    todays_meals: 'Comidas de hoy',
    log_meal: 'Registrar comida',
    breakfast: 'Desayuno',
    snack: 'Snack',
    lunch: 'Almuerzo',
    afternoon: 'Merienda',
    dinner: 'Cena',
    // progress
    progress: 'Progreso',
    body_weight: 'Peso corporal',
    body_fat: '% Grasa',
    measurements: 'Medidas',
    waist: 'Cintura',
    chest: 'Pecho',
    arm: 'Brazo',
    thigh: 'Muslo',
    hip: 'Cadera',
    neck: 'Cuello',
    cm: 'cm',
    kg: 'kg',
    pct: '%',
    photos: 'Fotos de progreso',
    front: 'Frente',
    side: 'Lado',
    back: 'Espalda',
    add_photo: 'Añadir foto',
    last: 'última',
    goal: 'meta',
    // hydration
    hydration: 'Hidratación',
    glasses: 'vasos',
    of_target: 'de',
    // calendar
    cal_week: 'Semana en curso',
    rest_day: 'Descanso',
    push: 'Push',
    pull: 'Pull',
    legs: 'Piernas',
    full_body: 'Full body',
    cardio: 'Cardio',
    mobility: 'Movilidad',
    // dow
    dow: ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'],
    // coach
    coach_overview: 'Panorama del día',
    active_clients: 'Clientes activos',
    sessions_today: 'Sesiones hoy',
    avg_adherence: 'Adherencia media',
    new_msgs: 'Mensajes sin leer',
    your_clients: 'Tus clientes',
    client_col: 'Cliente',
    plan_col: 'Plan',
    adherence_col: 'Adherencia',
    progress_col: 'Δ peso',
    last_active: 'Última actividad',
    status_col: 'Estado',
    on_track: 'Al día',
    behind: 'Atrasado',
    rest_today: 'Descanso',
    today_session: 'Hoy',
    quick_actions: 'Acciones rápidas',
    assign_routine: 'Asignar rutina',
    create_plan: 'Crear plan',
    send_message: 'Enviar mensaje',
    log_metric: 'Registrar métrica',
    today_sessions: 'Sesiones de hoy',
    no_sessions: 'No hay sesiones programadas',
    // welcome banner
    today_kcal: 'Kcal hoy',
    today_weight: 'Peso',
    streak_label: 'Racha',
    workouts_week: 'Entrenos / semana',
    coach_greeting: 'Buen día, coach',
    // screen titles
    screen: {
      routine_title: 'Rutina activa',
      routine_sub: 'Sigue tus series en tiempo real, registra cargas y deja notas para tu coach.',
      meals_title: 'Plan de alimentación',
      meals_sub: 'Macros y comidas planificadas para hoy. Personalizable según tus preferencias.',
      progress_title: 'Tu progreso',
      progress_sub: 'Peso, composición corporal, medidas e hidratación — todo en un solo lugar.',
      calendar_title: 'Calendario',
      calendar_sub: 'Vista mensual de tu plan. Reorganiza días manteniendo pulsado.',
      clients_title: 'Tus clientes',
      clients_sub: 'Gestiona adherencia, planes y mensajes desde una sola tabla.',
      sessions_title: 'Sesiones',
      sessions_sub: 'Agenda semanal · arrastra para reorganizar.',
      library_title: 'Biblioteca',
      plans_title: 'Plantillas',
    },
  },
  en: {
    appName: 'PULSE/',
    tagline: 'Training. Nutrition. Results.',
    perspective: { client: 'Client', coach: 'Coach' },
    nav: {
      group_main: 'Main',
      home: 'Home',
      routine: 'Routine',
      meals: 'Nutrition',
      progress: 'Progress',
      calendar: 'Calendar',
      group_other: 'More',
      messages: 'Messages',
      settings: 'Settings',
      group_coach: 'Coaching',
      clients: 'Clients',
      sessions: 'Sessions',
      library: 'Library',
      plans: 'Templates',
    },
    search: 'Search exercise, food, client…',
    greeting_morning: 'Good morning',
    greeting_afternoon: 'Good afternoon',
    greeting_evening: 'Good evening',
    today: 'Today',
    week: 'This week',
    streak: 'streak',
    days_short: 'd',
    phase: 'Phase',
    phases: { hyper: 'Hypertrophy', cut: 'Cut', maint: 'Maintenance', strength: 'Strength' },
    objective: 'Goal',
    objectives: { lose: 'Lose fat', gain: 'Build muscle', maint: 'Maintain' },
    day_n: 'Day',
    of: 'of',
    todays_routine: "Today's routine",
    routine_meta: 'exercises',
    minutes: 'min',
    start_workout: 'Start workout',
    finish_workout: 'Finish',
    sets: 'Sets',
    reps: 'Reps',
    weight: 'Weight',
    rest: 'Rest',
    rest_label: 'Rest',
    set_num: 'Set',
    last_session: 'Last session',
    pr: 'PR',
    notes: 'Notes',
    set_done: 'Done',
    nutrition: 'Nutrition',
    calories: 'Calories',
    kcal: 'kcal',
    macro_p: 'Protein',
    macro_c: 'Carbs',
    macro_f: 'Fat',
    g_unit: 'g',
    todays_meals: "Today's meals",
    log_meal: 'Log meal',
    breakfast: 'Breakfast',
    snack: 'Snack',
    lunch: 'Lunch',
    afternoon: 'Afternoon',
    dinner: 'Dinner',
    progress: 'Progress',
    body_weight: 'Body weight',
    body_fat: 'Body fat',
    measurements: 'Measurements',
    waist: 'Waist',
    chest: 'Chest',
    arm: 'Arm',
    thigh: 'Thigh',
    hip: 'Hip',
    neck: 'Neck',
    cm: 'cm',
    kg: 'kg',
    pct: '%',
    photos: 'Progress photos',
    front: 'Front',
    side: 'Side',
    back: 'Back',
    add_photo: 'Add photo',
    last: 'last',
    goal: 'goal',
    hydration: 'Hydration',
    glasses: 'glasses',
    of_target: 'of',
    cal_week: 'Current week',
    rest_day: 'Rest',
    push: 'Push',
    pull: 'Pull',
    legs: 'Legs',
    full_body: 'Full body',
    cardio: 'Cardio',
    mobility: 'Mobility',
    dow: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    coach_overview: "Today's overview",
    active_clients: 'Active clients',
    sessions_today: 'Sessions today',
    avg_adherence: 'Avg. adherence',
    new_msgs: 'Unread messages',
    your_clients: 'Your clients',
    client_col: 'Client',
    plan_col: 'Plan',
    adherence_col: 'Adherence',
    progress_col: 'Δ weight',
    last_active: 'Last active',
    status_col: 'Status',
    on_track: 'On track',
    behind: 'Behind',
    rest_today: 'Rest',
    today_session: 'Today',
    quick_actions: 'Quick actions',
    assign_routine: 'Assign routine',
    create_plan: 'Create plan',
    send_message: 'Send message',
    log_metric: 'Log metric',
    today_sessions: "Today's sessions",
    no_sessions: 'No sessions scheduled',
    today_kcal: 'Calories today',
    today_weight: 'Weight',
    streak_label: 'Streak',
    workouts_week: 'Workouts / week',
    coach_greeting: 'Good day, coach',
    screen: {
      routine_title: 'Active routine',
      routine_sub: 'Track sets in real time, log loads, and leave notes for your coach.',
      meals_title: 'Meal plan',
      meals_sub: 'Macros and planned meals for today. Adjustable to your preferences.',
      progress_title: 'Your progress',
      progress_sub: 'Weight, body composition, measurements & hydration — all in one place.',
      calendar_title: 'Calendar',
      calendar_sub: 'Monthly view of your plan. Long-press to reorder.',
      clients_title: 'Your clients',
      clients_sub: 'Manage adherence, plans and messages from a single table.',
      sessions_title: 'Sessions',
      sessions_sub: 'Weekly schedule · drag to rearrange.',
      library_title: 'Library',
      plans_title: 'Templates',
    },
  },
};

// ── Mock data ──────────────────────────────────────────────────────────────

window.MOCK = {
  client: {
    initials: 'SM',
    tone: 'a',
    objective: 'gain', // matches I18N.objectives keys
    phase: 'hyper',
    day: 24,
    plan_total: 84,
    streak: 12,
    workouts_done_week: 4,
    workouts_target_week: 5,
    weight_today: 64.2,
    weight_delta_30d: -1.8, // kg
    weight_goal: 62,
    bf_today: 22.4,
    bf_delta: -1.2,
    kcal_today: 1840,
    kcal_target: 2200,
    macros: {
      protein: { value: 142, target: 165 },
      carbs:   { value: 188, target: 240 },
      fat:     { value: 56,  target: 65  },
    },
    hydration: { glasses: 5, target: 8 },
    measurements: [
      { key: 'waist', val: 71.5, delta: -1.5 },
      { key: 'chest', val: 92,   delta: +0.8 },
      { key: 'arm',   val: 30.2, delta: +0.4 },
      { key: 'thigh', val: 56,   delta: +0.7 },
      { key: 'hip',   val: 96,   delta: -0.6 },
      { key: 'neck',  val: 33,   delta: 0    },
    ],
    weight_series: [
      66.0, 65.8, 66.1, 65.6, 65.4, 65.5, 65.0, 64.7, 64.9, 64.5, 64.3, 64.2,
    ],
    bf_series: [
      23.6, 23.5, 23.4, 23.2, 23.1, 22.9, 22.8, 22.7, 22.6, 22.5, 22.5, 22.4,
    ],
    photos: [
      { label: 'front', date: '14 ABR' },
      { label: 'side',  date: '14 ABR' },
      { label: 'back',  date: '14 ABR' },
    ],
    routine: {
      name_es: 'Push A · Pecho/Hombro/Tríceps',
      name_en: 'Push A · Chest/Shoulder/Triceps',
      duration_min: 52,
      exercises: [
        { name_es: 'Press banca con barra', name_en: 'Barbell bench press',
          sets: 4, reps: '6–8', weight: 52.5, status: 'done',
          done_sets: [{ w: 50, r: 8, ok: true }, { w: 52.5, r: 7, ok: true }, { w: 52.5, r: 6, ok: true }, { w: 52.5, r: 6, ok: true }] },
        { name_es: 'Press inclinado mancuernas', name_en: 'Incline DB press',
          sets: 3, reps: '8–10', weight: 18, status: 'active',
          done_sets: [{ w: 18, r: 10, ok: true }, { w: 18, r: 9, ok: true }, { w: 18, r: 0, ok: false }],
          last_session: '3 × 18kg × 9·9·8' },
        { name_es: 'Press militar máquina', name_en: 'Machine shoulder press',
          sets: 3, reps: '10–12', weight: 32, status: 'pending' },
        { name_es: 'Aperturas en polea', name_en: 'Cable fly',
          sets: 3, reps: '12–15', weight: 12, status: 'pending' },
        { name_es: 'Extensión de tríceps en polea', name_en: 'Triceps pushdown',
          sets: 3, reps: '12', weight: 24, status: 'pending' },
        { name_es: 'Elevación lateral mancuernas', name_en: 'Lateral raise',
          sets: 4, reps: '15', weight: 8, status: 'pending' },
      ],
    },
    meals: [
      { time: '07:30', name_es: 'Avena con frutos rojos', name_en: 'Oats with berries',
        desc_es: 'Avena · plátano · whey · arándanos', desc_en: 'Oats · banana · whey · blueberries',
        kcal: 480, logged: true, type: 'breakfast' },
      { time: '11:00', name_es: 'Yogur griego + nueces', name_en: 'Greek yogurt + nuts',
        desc_es: '200g yogur · 20g nueces', desc_en: '200g yogurt · 20g walnuts',
        kcal: 310, logged: true, type: 'snack' },
      { time: '14:00', name_es: 'Pollo con arroz y verduras', name_en: 'Chicken with rice & veg',
        desc_es: '180g pollo · 90g arroz · brócoli', desc_en: '180g chicken · 90g rice · broccoli',
        kcal: 620, logged: true, type: 'lunch' },
      { time: '17:30', name_es: 'Smoothie post-entreno', name_en: 'Post-workout smoothie',
        desc_es: 'Whey · plátano · leche almendra', desc_en: 'Whey · banana · almond milk',
        kcal: 280, logged: false, type: 'snack' },
      { time: '20:30', name_es: 'Salmón con boniato', name_en: 'Salmon with sweet potato',
        desc_es: '150g salmón · 200g boniato · ensalada', desc_en: '150g salmon · 200g sweet potato · salad',
        kcal: 540, logged: false, type: 'dinner' },
    ],
    week: [
      { dow: 0, num: 5,  workout: 'pull',     dur: '48 min', done: true },
      { dow: 1, num: 6,  workout: 'rest',     dur: '',       done: false },
      { dow: 2, num: 7,  workout: 'legs',     dur: '64 min', done: true },
      { dow: 3, num: 8,  workout: 'mobility', dur: '20 min', done: true },
      { dow: 4, num: 9,  workout: 'push',     dur: '52 min', done: false, today: true },
      { dow: 5, num: 10, workout: 'cardio',   dur: '30 min', done: false },
      { dow: 6, num: 11, workout: 'rest',     dur: '',       done: false },
    ],
  },
  coach: {
    initials: 'MR',
    name: 'Marco Ruiz',
    active_clients: 12,
    sessions_today: 4,
    avg_adherence: 87,
    unread_msgs: 3,
    delta_clients: '+2 mes',
    delta_adherence: '+4 pp',
    today_sessions: [
      { time: '09:00', client: 'Sofía Martín', initials: 'SM', tone: 'a', what_es: 'Push A · Hipertrofia', what_en: 'Push A · Hypertrophy' },
      { time: '11:30', client: 'Lucas Vidal',  initials: 'LV', tone: 'b', what_es: 'Plan inicial · evaluación', what_en: 'Initial plan · assessment' },
      { time: '15:00', client: 'Andrea León',  initials: 'AL', tone: 'c', what_es: 'Pull B · Fuerza', what_en: 'Pull B · Strength' },
      { time: '18:30', client: 'Tomás Iglesias', initials: 'TI', tone: 'd', what_es: 'Movilidad · revisión', what_en: 'Mobility · review' },
    ],
    clients: [
      { name: 'Sofía Martín', email: 'sofia.m@mail.com', initials: 'SM', tone: 'a',
        plan_es: 'Hipertrofia 12s', plan_en: 'Hypertrophy 12w', plan_week: 'S 4/12',
        adherence: 92, delta_kg: -1.8, last_active: 'hace 2h', last_active_en: '2h ago',
        status: 'on-track', today: 'push' },
      { name: 'Lucas Vidal', email: 'lucas.v@mail.com', initials: 'LV', tone: 'b',
        plan_es: 'Inicial · onboarding', plan_en: 'Initial · onboarding', plan_week: 'S 1/8',
        adherence: 78, delta_kg: -0.4, last_active: 'hace 5h', last_active_en: '5h ago',
        status: 'on-track', today: 'session' },
      { name: 'Andrea León', email: 'a.leon@mail.com', initials: 'AL', tone: 'c',
        plan_es: 'Fuerza 5×5', plan_en: 'Strength 5×5', plan_week: 'S 7/10',
        adherence: 95, delta_kg: +1.2, last_active: 'hace 1d', last_active_en: '1d ago',
        status: 'on-track', today: 'pull' },
      { name: 'Tomás Iglesias', email: 't.igl@mail.com', initials: 'TI', tone: 'd',
        plan_es: 'Movilidad + cardio', plan_en: 'Mobility + cardio', plan_week: 'S 2/6',
        adherence: 64, delta_kg: -0.2, last_active: 'hace 3d', last_active_en: '3d ago',
        status: 'warn', today: 'mobility' },
      { name: 'Carla Bahena', email: 'c.bahena@mail.com', initials: 'CB', tone: 'e',
        plan_es: 'Definición 8s', plan_en: 'Cut 8w', plan_week: 'S 6/8',
        adherence: 88, delta_kg: -3.4, last_active: 'hace 6h', last_active_en: '6h ago',
        status: 'on-track', today: 'rest' },
      { name: 'Diego Salas', email: 'diego.s@mail.com', initials: 'DS', tone: 'f',
        plan_es: 'Hipertrofia 12s', plan_en: 'Hypertrophy 12w', plan_week: 'S 9/12',
        adherence: 41, delta_kg: +0.8, last_active: 'hace 4d', last_active_en: '4d ago',
        status: 'behind', today: 'legs' },
      { name: 'Elena Roca', email: 'eroca@mail.com', initials: 'ER', tone: 'b',
        plan_es: 'Mantenimiento', plan_en: 'Maintenance', plan_week: 'continuo',
        adherence: 96, delta_kg: -0.1, last_active: 'hace 30m', last_active_en: '30m ago',
        status: 'on-track', today: 'cardio' },
      { name: 'Marc Soler', email: 'msoler@mail.com', initials: 'MS', tone: 'c',
        plan_es: 'Inicial · onboarding', plan_en: 'Initial · onboarding', plan_week: 'S 2/8',
        adherence: 72, delta_kg: -0.6, last_active: 'hace 8h', last_active_en: '8h ago',
        status: 'warn', today: 'rest' },
      { name: 'Júlia Pons', email: 'j.pons@mail.com', initials: 'JP', tone: 'd',
        plan_es: 'Hipertrofia 12s', plan_en: 'Hypertrophy 12w', plan_week: 'S 3/12',
        adherence: 90, delta_kg: +0.4, last_active: 'hace 1h', last_active_en: '1h ago',
        status: 'on-track', today: 'pull' },
    ],
    adherence_series: [82, 84, 83, 86, 88, 87, 85, 88, 89, 87, 87, 87],
  },
};
